# Generated by Django 4.1.7 on 2023-05-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="air",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
