# Generated by Django 2.2.6 on 2023-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airCode', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('reserve1', models.CharField(max_length=100)),
                ('reserve2', models.CharField(max_length=100)),
                ('reserve3', models.CharField(max_length=100)),
                ('reserve4', models.CharField(max_length=100)),
                ('reserve5', models.CharField(max_length=100)),
                ('comCode', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('fliAaddress', models.CharField(max_length=100)),
                ('fliAtime', models.CharField(max_length=100)),
                ('fliBaddress', models.CharField(max_length=100)),
                ('fliBtime', models.CharField(max_length=100)),
                ('fliCfare', models.CharField(max_length=100)),
                ('fliCnumber', models.CharField(max_length=100)),
                ('fliDiscount', models.CharField(max_length=100)),
                ('fliFfare', models.CharField(max_length=100)),
                ('fliFnumber', models.CharField(max_length=100)),
                ('fliNo', models.CharField(max_length=100)),
                ('fliRefundtime', models.CharField(max_length=100)),
                ('fliYfare', models.CharField(max_length=100)),
                ('fliYnumber', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flight',
                'db_table': 'flight',
            },
        ),
    ]
